<?xml version="1.0" encoding="utf-8"?><Database Name="Bhavesh" Class="dbLinQtoSQLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=192.168.1.20;Initial Catalog=Bhavesh;Persist Security Info=True;User ID=Bhavesh" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BhaveshConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblDemo" Member="tblDemos">
    <Type Name="tblDemo">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="gender" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="hobbies" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
    </Type>
  </Table>
</Database>